# Generated by Django 5.2.4 on 2025-07-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del equipo', max_length=100)),
                ('entrenador', models.CharField(help_text='Nombre del entrenador', max_length=100)),
                ('escudo', models.ImageField(help_text='Escudo del equipo', upload_to='escudos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del país', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del jugador', max_length=100)),
                ('edad', models.IntegerField(help_text='Edad del jugador')),
                ('posicion', models.CharField(help_text='Posición en la que juega el jugador', max_length=100)),
                ('foto', models.ImageField(help_text='Foto del jugador', upload_to='fotos/')),
                ('equipo', models.ForeignKey(help_text='Equipo en el que juega el jugador', on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.equipo')),
                ('pais', models.ForeignKey(help_text='País de origen del jugador', on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.pais')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='pais',
            field=models.ForeignKey(help_text='País al que pertenece el equipo', on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.pais'),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del torneo', max_length=100)),
                ('pais', models.ForeignKey(help_text='País en el que se juega el torneo', on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del partido')),
                ('goles_local', models.IntegerField(default=0, help_text='Goles del equipo local')),
                ('goles_visitante', models.IntegerField(default=0, help_text='Goles del equipo visitante')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='registro_futbol.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='registro_futbol.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_futbol.torneo')),
            ],
            options={
                'unique_together': {('equipo', 'torneo')},
            },
        ),
    ]
