# Generated by Django 5.2.4 on 2025-07-11 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(help_text='Edad del jugador', validators=[django.core.validators.MaxValueValidator(46), django.core.validators.MinValueValidator(16)]),
        ),
    ]
